version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - fullstack-network

  back-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: back-ventas
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=mysql-db
      - DB_PORT=3306
      - DB_NAME=mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - fullstack-network

  back-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: back-despachos
    ports:
      - "8081:8081"
    environment:
      - DB_ENDPOINT=mysql-db
      - DB_PORT=3306
      - DB_NAME=mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - fullstack-network

  front-despacho:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: front-despacho
    ports:
      - "5173:80"
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge

volumes:
  db_data:
