version: '3.8'

services:
  
  db-ventas:
    image: mysql:8.0
    container_name: db-ventas
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: ventas_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_ventas_data:/var/lib/mysql
      - ./init-db/seed-ventas.sql:/docker-entrypoint-initdb.d/seed.sql

  db-despachos:
    image: mysql:8.0
    container_name: db-despachos
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: despachos_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306" 
    volumes:
      - db_despachos_data:/var/lib/mysql
      - ./init-db/seed-despachos.sql:/docker-entrypoint-initdb.d/seed.sql

  
  back-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: back-ventas
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=db-ventas 
      - DB_PORT=3306
      - DB_NAME=ventas_db
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword

  back-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: back-despachos
    ports:
      - "8081:8081"
    environment:
      - DB_ENDPOINT=db-despachos 
      - DB_PORT=3306
      - DB_NAME=despachos_db
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword

  
  front-despacho:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: front-despacho
    ports:
      - "5173:80"

volumes:
  db_ventas_data:
  db_despachos_data:
